### ISSUE TITLE
Can't handle WebSocket connection

### ISSUE THREAD

**Issue by bonyfr** [mitre/HTTP-Proxy-Servlet#100]
I'm trying to use your reverse proxy, but it doesn't work with Websocket connection.

Do you have some idea to do it ?

Eric

**Comment by dsmiley** [comment]
Sorry I have no idea.  If you work on it and submit a PR, I would gladly take a look.

FYI also asked in #88

**Comment by dsmiley** [comment]
This is really a duplicate of that issue so I'll close it.
