### ISSUE TITLE
Cannot retry request with a non-repeatable request entity

### ISSUE THREAD

**Issue by holy-silent** [mitre/HTTP-Proxy-Servlet#109]
When i use HTTP-Proxy-Servlet,I met the error ："Cannot retry request with a non-repeatable request entity",i don't know how to solve it. Maybe the reason is that you use the class InputStreamEntity.Please look at the following：
`protected HttpRequest newProxyRequestWithEntity(String method, String proxyRequestUri,
                                                HttpServletRequest servletRequest)
          throws IOException {
    HttpEntityEnclosingRequest eProxyRequest =
            new BasicHttpEntityEnclosingRequest(method, proxyRequestUri);
    // Add the input entity (streamed)
    //  note: we don't bother ensuring we close the servletInputStream since the container handles it
    eProxyRequest.setEntity(
            new InputStreamEntity(servletRequest.getInputStream(), getContentLength(servletRequest)));
    return eProxyRequest;
 }`

**Comment by dsmiley** [comment]
#67 is related.
I have no real answer for you; I don't have much time for this project right now.

**Comment by holy-silent** [comment]
All right, thank you.
