### ISSUE TITLE
Publish v1.9

### ISSUE THREAD

**Issue by markncsu** [mitre/HTTP-Proxy-Servlet#116]
Are there plans to push the current code to Maven?  Looks like the last update to Maven (version 1.8) was in August.  I'm specifically looking to take advantage of the cookie preservation code added in November.  Thanks.

**Comment by dsmiley** [comment]
Ah; I've just been busy. Thanks for filing an issue (this one).  I'll see if I can get in anything small/easy and do a release "real soon now" (famous last words); no sooner than this coming weekend though.

**Comment by markncsu** [comment]
That would fantastic.  Thanks so much!

**Comment by dsmiley** [comment]
I'll publish Monday afternoon, thus giving a little bit more time for people to react to my changes this weekend.

**Comment by dsmiley** [comment]
v1.9 is now official.  It should be on Maven Central within a couple hours.
