### ISSUE TITLE
Browser configuration: How to config firefox to use this proxy?

### ISSUE THREAD

**Issue by jackzhp** [mitre/HTTP-Proxy-Servlet#120]
I am not sure how to configure my firefox to use this proxy.

Suppose the proxy is at http://www.abc.com/www.def.com/ for http://www.def.com/
and https://www.abc.com/www.def.com/ for https://www.def.com/

How do I configure my firefox to use the proxy?

I know for other cases, for example for Squid, I set www.abc.com:3128 to the firefox, and everything works. But for this servlet proxy, how?

Thanks.

**Comment by dsmiley** [comment]
The "HTTP Proxy Servlet" here is a "Reverse Proxy".  You want a "forward proxy".  A forward proxy doesn't fit with the intended use-case of this servlet.
http://stackoverflow.com/a/366212/92186
