### ISSUE TITLE
Can I proxy some request with some specific param and value?

### ISSUE THREAD

**Issue by denghuichao** [mitre/HTTP-Proxy-Servlet#129]
I have some rest api in Spring MVC, where there is a param named 'env' and its value is dev, qa or prod. So, the request URL is like http://srcHost/api/hello?env={#env}.  I want to proxy the request where 'env' is dev or qa to other server, like http://targetHost/api/hello?env=qa. Can I use this project to do this?

**Comment by dsmiley** [comment]
Yes, see URITemplateProxyServlet

**Comment by denghuichao** [comment]
Thanks for your answer and this actually works in some case. But how if the request is POST and the env param is not in the query string?

**Comment by denghuichao** [comment]
Thanks for your answer and this actually works in some case. But how if the request is POST and the env param is not in the query string?

**Comment by dsmiley** [comment]
Oh I see.  Well you could file a PR if you'd like to contribute such an enhancement.
