### ISSUE TITLE
wrong ?null= query string added to proxy URL

### ISSUE THREAD

**Issue by pjunlin** [mitre/HTTP-Proxy-Servlet#132]
https://github.com/mitre/HTTP-Proxy-Servlet/blob/4bb8ff20b456843ccb8e1c0f62fc615465be6c01/src/main/java/org/mitre/dsmiley/httpproxy/URITemplateProxyServlet.java#L86

when servletRequest.getQueryString() is null, the correct behavior is make queryString = "", otherwise later the URI will always add "?null=" at the end of uri resulting issues in some case. e.g. Server side may only accept http://localhost:8080/abc and regard http://localhost:8080/abc?null= as a wrong uri.

**Comment by dsmiley** [comment]
Thanks for reporting. PR please.
