### ISSUE TITLE
Forward or reverse proxy? 

### ISSUE THREAD

**Issue by Hublo22** [mitre/HTTP-Proxy-Servlet#137]
From what I understood, you implemented a forward proxy, am I right? Or did I miss anything obvious... I don't see that it can be configured as a reverse one.

**Comment by Hublo22** [comment]
Is it possible to intercept an URL which is sent back to the user in order to rewrite it, so that the end-user never has any trace of the backing server? My problem is:

I have an application configured with your proxy. Everything which comes on /proxy/* is forwarded to my backing server. But the end user, using Chrome Debugging tool for example, will see the configured forwarded URL ... I want him to see another URL, so that it cannot access only a particular resource on my backing server (by using the forward proxy mechanism).

**Comment by Hublo22** [comment]
I mean something like this (Received response intercepting): https://github.com/mkopylec/charon-spring-boot-starter#received-response-intercepting

**Comment by dsmiley** [comment]
Even though this is a reverse proxy, it doesn't support that (sorry).  If you want to try to completely hide a website in such a way, you're better off looking elsewhere like to the project you identified.  A goal of the proxy here is to be very minimalist for better & worse.
