### ISSUE TITLE
HTTP Error code redirection

### ISSUE THREAD

**Issue by ghost** [mitre/HTTP-Proxy-Servlet#138]
Is it possible to set it up so that if the server I'm proxying to returns a 404 or other error code then the proxy will redirect to tomcats page for that error instead of the page the server behind the proxy responds with?

**Comment by dsmiley** [comment]
I *think* so... this would be in the realm of customization via subclassing.

**Comment by Scoopta** [comment]
Hmmm alright I'll take a look and see if I can figure something out for that then.
