### ISSUE TITLE
Add support for configuring networking-related behavior of Apache HTTP client from JVM system properties

### ISSUE THREAD

**Issue by twwwt** [mitre/HTTP-Proxy-Servlet#139]
Apache HTTP client supports setting various networking-related behavior from system properties defined by the JVM. As an example `http.proxyHost`, `https.proxyHost`, which are particularly needed if the proxy servlet itself is behind a HTTP forward proxy through which all traffic must be routed. For a list of system properties available, see [SystemDefaultHttpClient](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/SystemDefaultHttpClient.html).

Whether these system properties are taken into account should be configurable using a new init Boolean parameter `useSystemProperties`. If `true` the system properties are taken into account; if `false` not, even if they are set.

**Comment by twwwt** [comment]
Now that this has been merged, would it be possible to do a new release?

Thanks

**Comment by dsmiley** [comment]
Yeah, soon-ish.

**Comment by dsmiley** [comment]
I plan to release in a week or two.  I invite you to harass me if I don't ;-)
