### ISSUE TITLE
Add ability to override reg.getPathInfo()

### ISSUE THREAD

**Issue by orenefraty** [mitre/HTTP-Proxy-Servlet#148]
Add new method to ProxyServlet:

protected  String computePathInfoEncoded(HttpServletRequest req) {
  return encodeUriQuery(req.getPathInfo());
}

To allow manipulating req.getPathInfo()

**Comment by dsmiley** [comment]
Sounds good.  Pull requests welcome.  Also include Javadocs to inform users what it's for and why they might subclass it.
