### ISSUE TITLE
Could you please make a release?

### ISSUE THREAD

**Issue by aindlq** [mitre/HTTP-Proxy-Servlet#168]
Could you please make a new release? There was a nice PR that was merged in the beginning of this year (https://github.com/mitre/HTTP-Proxy-Servlet/pull/158) and it would be really great to have it officially released.

Thanks!

**Comment by dsmiley** [comment]
Indeed, another release would be good.  I updated my email filters a year ago and I'm now realizing stuff has fallen through the cracks, so sorry for the delay.  I will tend to some other PRs before doing a release.

**Comment by asashour** [comment]
I guess this should be closed.
