### ISSUE TITLE
copyResponseHeader method is copying only first Set-Cookie header if the response has multiple Set-Cookie headers

### ISSUE THREAD

**Issue by urachakonda** [mitre/HTTP-Proxy-Servlet#174]
The current copyResponse method is getting header value to a string instead of List<String> causing issues in setting only first header value and ignoring the rest.

**Comment by dsmiley** [comment]
What exactly should it do (in more detail than what you said)?  Sorry but it's not obvious to me.  "Header" is a particular name-value pair and there may be multiple such Headers having the same name.

**Comment by urachakonda** [comment]
Yes, "Header" is a particular name-value pair and there may be multiple such Headers having the same name.

When copying the response headers, the copyResponseHeader method is getting the value of a header to a string, it should supposed to a List<String>. Because when we add a header, we can add multiple headers with same name, but when retrieving, if we get the header value to a string, it gets only the first header and ignore the rest. 

``` JAVA
  protected void copyResponseHeader(HttpServletRequest servletRequest, HttpServletResponse servletResponse, Header header) {
    **String headerName = header.getName();**
    if (!hopByHopHeaders.containsHeader(headerName)) {
      String headerValue = header.getValue();
      if (!headerName.equalsIgnoreCase("Set-Cookie") && !headerName.equalsIgnoreCase("Set-Cookie2")) {
        if (headerName.equalsIgnoreCase("Location")) {
          servletResponse.addHeader(headerName, this.rewriteUrlFromResponse(servletRequest, headerValue));
        } else {
          servletResponse.addHeader(headerName, headerValue);
        }
      } else {
        this.copyProxyCookie(servletRequest, servletResponse, headerValue);
      }

    }
  }
```

**Comment by urachakonda** [comment]
There was a different issue causing problem to me on this, and I figured out that apache Headers will retrieve all same name headers too unlike springframework HttpHeaders where it has a list.
Closing the issue since there was no real issue on this.
