### ISSUE TITLE
“post + application/x-www-form-urlencoded” bug

### ISSUE THREAD

**Issue by yulongcc** [mitre/HTTP-Proxy-Servlet#185]
if a request consist of post + application/x-www-form-urlencoded，servlet will read inputstream into request paramters，then the proxyrequest can not read the inputstream again.

**Comment by schouk** [comment]
I found more information here (seems to be a duplicate): https://github.com/mitre/HTTP-Proxy-Servlet/issues/54
It is not 'solved', but there are proposals for different solutions.
