### ISSUE TITLE
Encoded question marks in path are not encoded from proxy

### ISSUE THREAD

**Issue by fpetterlate** [mitre/HTTP-Proxy-Servlet#190]
If I try to do a request on:

`https://localhost:8084/proxy/api/pathwithquestionmark%3F%3F?from=1&to=10`

I see in the log that I get:
`proxy GET uri: /proxy/api/pathwithquestionmark%3F%3F -- https://my.server.com/api/pathwithquestionmark???from=1&to=10`

So it looks like questions marks in path are not encoded anymore.

**Comment by dsmiley** [comment]
Fixed!  Thanks for reporting the problem!

**Comment by fpetterlate** [comment]
Thanks :) Will there be a release soon?

**Comment by dsmiley** [comment]
I created #193 for the release.
