### ISSUE TITLE
ProxyServlet.P_TARGET_URI not accessible as it's package visible

### ISSUE THREAD

**Issue by OLibutzki** [mitre/HTTP-Proxy-Servlet#192]
I want to register a the ProxyServlet in a SpringBoot application using this approach: https://github.com/mitre/HTTP-Proxy-Servlet#spring-boot

Unfortunately, ProxyServlet.P_TARGET_URI is not public visible and I have to use the String "targetUri" instead of the constant.

Is this intended?

**Comment by dsmiley** [comment]
That's odd indeed!  I fixed it.

**Comment by OLibutzki** [comment]
Thanks!
