### ISSUE TITLE
Question: Use to proxy webcams

### ISSUE THREAD

**Issue by eitch** [mitre/HTTP-Proxy-Servlet#194]
I am building a home automation web application, which i use to set states on switches, etc. I have also added the function to start/stop recording of a webcam, and now i would like to be able to embed the webcam in the application. Would this HTTP-Proxy-Servlet be able to help me here? I would register the servlet to then connect to a webcam, to which only the server has access, not the clients connecting, and i can then enforce authorization by validating an HTTP header or some such.

Thanks for any tips.

**Comment by dsmiley** [comment]
Yes, it should work fine!
