### ISSUE TITLE
 Proxy post request Content-Type:x-www-form-urlencoded request body missing

### ISSUE THREAD

**Issue by GWsuperman** [mitre/HTTP-Proxy-Servlet#198]
POST request header is content-type:x-www-form-urlencoded request proxy is problematic. The main reason is that in the ProxyServlet.newProxyRequestWithEntity method when servletRequest. getInputStream ()  The byte stream read is empty, This causes the body of the request that later requests the real address to be lost. Google found that the body parameters of the x-www-form-urlencoded POST request go through servletRequest.getParameterMap() method gets it . Hopefully this will be fixed in later versions.  
Soory,  My English is poor, There may be some grammatical problems with the translation software, but I think you get the general idea.

**Comment by EdgewareRoad** [comment]
This has been dealt with before. See https://github.com/mitre/HTTP-Proxy-Servlet/issues/54

**Comment by GWsuperman** [comment]
> )
Thank you for your help 


> This has been dealt with before. See #54
> 
> Try turning off the HiddenHttpMethodFIlter ([#54 (comment)](https://github.com/mitre/HTTP-Proxy-Servlet/issues/54#issuecomment-518633794))

**Comment by GWsuperman** [comment]
> This has been dealt with before. See #54
> 
> Try turning off the HiddenHttpMethodFIlter ([#54 (comment)](https://github.com/mitre/HTTP-Proxy-Servlet/issues/54#issuecomment-518633794))

Thank you for your help
