### ISSUE TITLE
Proxy exposed on HTTP can't pass on Secure Cookies if the external service is HTTPS

### ISSUE THREAD

**Issue by EdgewareRoad** [mitre/HTTP-Proxy-Servlet#229]
Possibly a rare topology here but one I've experienced. The proxy on HTTP calling an external HTTPS service all worked fine until there was a change externally and cookies were returned with the Secure attribute set. As such, the proxy logic passes on this attribute and the underlying servlet and HTTP logic then throws the cookie away.

If the servlet request isSecure() method returns false, surely the Secure attribute should not be copied.

**Comment by EdgewareRoad** [comment]
Pull request #228 submitted for your consideration.

**Comment by dsmiley** [comment]
Thanks.  Makes sense to me.

**Comment by dsmiley** [comment]
At the next release I'll add a reference to this in the changes log.  It's kind of debatable if this is an enhancement or bug.

**Comment by EdgewareRoad** [comment]
Many thanks. Appreciate that, from different perspectives it could be either enhancement or bug. I’d make the case for this being more on the “bug” side on the basis that, if the “HTTP client, HTTPS service” topology is chosen, then without this proxy “fix”, the external service has to know how the proxy is configured, which seems wrong.  It’s only an enhancement if it’s generally practical/feasible to get your external service to change how they send cookies; not always true in my experience.

Many thanks again.

Phil

**Comment by dsmiley** [comment]
I wonder if people run in HTTP but fronted by some HTTPS proxy/gateway thing, so the client sees HTTP but the web server (running this servlet) doesn't know/care?
