### ISSUE TITLE
we think setConnectTimeout is wrong

### ISSUE THREAD

**Issue by dtbdtb** [mitre/HTTP-Proxy-Servlet#235]
hi :
we read code ,for 
![image](https://user-images.githubusercontent.com/6380023/209472493-d7abaf82-a003-4866-8022-c3708cea19d4.png)

**Comment by dsmiley** [comment]
yes.  "socketTimeout" is a somewhat generic in its name, thus in the proxy servlet, it's name is more specific.  By comparison, "connectTimeout" was a good name.
