### ISSUE TITLE
Jakarta EE 10 / Servlet spec 6.0 compatibility

### ISSUE THREAD

**Issue by mdindoffer** [mitre/HTTP-Proxy-Servlet#242]
We've been using a slightly modified version of this Proxy Servlet for quite some time with Jakarta EE 9.1 stack of libraries (Jetty 11) and it has worked fine.

However, we are now migrating to Jakarta EE 10 with Jetty 12 and Servlet spec 6.0. The current version of the proxy is built against Servlet spec 5.0 (Jakarta 9.1), which is raising some warnings:
- The [`Cookie#setComment`](https://github.com/mitre/HTTP-Proxy-Servlet/blob/b953eeb0842fcadc6a584014611b7b0782f145f8/src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java#L603) method has been *deprecated for removal* in Servlet 6.0, and is now [NO-OP](https://github.com/jakartaee/servlet/blob/8363ed338e6875f4e095b6cef8d9571f2fade82d/api/src/main/java/jakarta/servlet/http/Cookie.java#L147C17-L147C17)
- The [`Cookie#setVersion`](https://github.com/mitre/HTTP-Proxy-Servlet/blob/b953eeb0842fcadc6a584014611b7b0782f145f8/src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java#L607) method has been *deprecated for removal* in Servlet 6.0, and is now [NO-OP](https://github.com/jakartaee/servlet/blob/8363ed338e6875f4e095b6cef8d9571f2fade82d/api/src/main/java/jakarta/servlet/http/Cookie.java#L358)

What are the plans for supporting the newer JEE spec? Is it safe to just remove those deprecated calls?

**Comment by dsmiley** [comment]
Those are pretty minor.  There are no new plans but I went to the PR thread (#238)which chose spec 5 to ask why spec 5 and not newer specs.

**Comment by dsmiley** [comment]
https://github.com/mitre/HTTP-Proxy-Servlet/pull/238/files#r1085331506 6 is compatible with 5 and 5 was chosen deliberately for broad compatibility with servers.

**Comment by mdindoffer** [comment]
Well the touted backwards compatibility is arguable, as it only applies to non-deprecated methods and APIs, see e.g. [this article](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Top-5-things-to-know-about-the-Jakarta-Servlet-60-API-release) and [release notes](https://jakarta.ee/specifications/servlet/6.0/).

But, yes, I agree it makes sense to target v5.0. I was merely asking (from a position of someone who doesn't know a lot about the involved RFCs), what might be the impact on our application with those methods being NO-OP.
The same question could be applied to `HttpServletResponse#setStatus(int sc, String sm)` method, which has been previously deprecated and now removed from Servlet spec 6.0. That one was simply removed from the proxy in https://github.com/mitre/HTTP-Proxy-Servlet/pull/238/files#r1101714206

As there are no alternatives introduced, is the proxy slowly loosing features and not proxying all the data?

**Comment by dsmiley** [comment]
I sympathize with your point but these bits seem like minor metadata.  If you have ideas to solve them and are willing to make it happen, I'm listening.

**Comment by mdindoffer** [comment]
Yeah, I don't have any. I think I'll close this for now.
