### ISSUE TITLE
Removing deprecated method usage

### ISSUE THREAD

**Issue by manikantag** [mitre/HTTP-Proxy-Servlet#43]
Hi, in general, for several obvious reasons, as usage of deprecated API is discouraged, it is better to replace the deprecated API usages with new equivalent method.

**Comment by dsmiley** [comment]
Hi. It's deliberate for backwards compatibility; I'd like to have one version of this servlet compatible with a range of HttpClient versions.

**Comment by manikantag** [comment]
Fair enough. Thanks.
