### ISSUE TITLE
Does this proxy have any facilities for rewriting HTML links?

### ISSUE THREAD

**Issue by JoeJErnst** [mitre/HTTP-Proxy-Servlet#46]
I'm looking for a Java alternative to Apache's mod_proxy_html that can transform hyperlinks within the HTML of the remote site so that it works on my domain.  Does this servlet do that, or is is compatible with another library that does?

**Comment by dsmiley** [comment]
Ah, this proxy wasn't designed for this purpose; it passes-through the content.  I'm not sure about hyperlink rewriting alternatives.

**Comment by melin** [comment]
There are implementations in hadoop. Would consider support?

https://github.com/hopshadoop/hops/blob/master/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-web-proxy/src/main/java/org/apache/hadoop/yarn/server/webproxy/WebAppProxyServlet.java

**Comment by dsmiley** [comment]
I'm concerned such a feature would be too complex than the limited scope of this servlet.  Can you point to where in that servlet this logic happens?
