### ISSUE TITLE
Handling unnecessary "?" signs

### ISSUE THREAD

**Issue by Amberize** [mitre/HTTP-Proxy-Servlet#63]
I configure URITemplateProxyServlet like this:

``` xml
<init-param>
    <param-name>targetUri</param-name>
    <param-value>{_server}</param-value>
</init-param>
```

So I have to provide _server param via ?_server=<some url>. But while using Dojo Framework with dgrid I faced a problem that once I assigned some url to dgid, it would consider that url to be a "path without any query params". And while sorting or performing other queries dgid adds ?sort=(+param) for example. This way if I have url like this:

http://localhost:8080?num=?sort=(+param)

To get rid of this behaviour of some frameworks I suggest to filter any occurence of "?" sign in query string like this:

``` Java
Integer indexOfQuerySign = queryString.indexOf("?");
queryString = queryString.substring(0, indexOfQuerySign+1) + queryString.substring(indexOfQuerySign+1).replaceAll("\\?", "&");
```

**Comment by dsmiley** [comment]
Hmm.  This seems like a limitation/issue with Dojo Framework, not with the proxy servlet.
