### ISSUE TITLE
Complex issues with handling Redirects from back-end

### ISSUE THREAD

**Issue by l-dobrev** [mitre/HTTP-Proxy-Servlet#70]
1. The default Proxy Servlet handles back-end redirects internally and serves the redirected URL as if it was the original URL. This leads to numerous problems such as:
* third-party authentication (OAUTH*, OpenID, OpenID-Connect, SAML, etc.)
* relative URLs in documents (browser resolves them against the original URL)
  browser requests: http://proxy/path
  proxy requests: http://server/path
  server responds: 302 http://server/path/
  proxy requests: http://server/path/
  proxy returns contents.
  Relative URLs are now resolved against the original and improper base resulting in erroneous result.

Solution: supply the "http.protocol.handle-redirects" to "false" via servlet parameters

After applying this "solution" other problems arise:

2. Servers are allowed to return a Body on responses that contain a HTTP Redirect response code.
* Proxy Servlet instead uses HttpServletResponse.sendRedirect(String) which does not allow body, but in the mean time copies the Content-Length header from the back-end. This leads to clients hanging indefinitely waiting for the body of the response.
- Solution one: delete the Content-Length from the headers before sending redirect.
- Solution two: after performing redirect handling (with URL rewriting) copy the HTTP Entity to the client.

3. If the server returns a redirect to an URL that has encoded characters (like %20) the calculated redirection URL is wrong
 browser requests: http://proxy/some%20directory
 proxy requests: http://server/some%20directory
 server responds: 302 http://server/some%20directory/
 proxy responds: 302 http://proxy/s/some%20directory/
 which is obviously incorrect.

The problem becomes unmanageable if the URLs contain UTF-8 or other type of binary encoded content.
There is an assert ...ProxyServlet.rewriteUrlFromResponse(HttpServletRequest, String) on line 550, that should have pointed this out.

I do believe none of the above problems are niche or out-of-the-ordinary use cases.

I have worked-around problem 1 as noted, and have worked around problem 2 with a sub-class (I can provide code for review, but the code style is significantly different).
As for problem 3 it seems very awkward, so I'd like to hear from the developers before attempting to assume anything. The encoding problem might have been addresses in other issues (I've seen references), but I am not sure if those are connected or not.

**Comment by dsmiley** [comment]
Thanks for the thorough report!

I think handle-redirects should be disabled by default, now that I see all that can go wrong.

I'd be interested in a pull-request on your second point RE content-length / handling redirect responses.  This aspect of the proxy was copied from elsewhere with a comment.

RE URL encoding: In your example I don't see where the inserted 's/' came from.  But nonetheless there is at least one open issue about a known URL escaping bug.  There might need to be multiple modes of URL encoding; not sure.  I'd be interested to know what Apache mod-proxy does; it's approach may be worth emulating.

**Comment by l-dobrev** [comment]
For the additional /s in the URL on redirects. It comes out because the Proxy Servlet strips from the URL a certain number of characters, which is taken from the original request URL, removing the request. However the number of characters that need to be removed is taken from the pathInfo, which is URL-Decoded, but the number of characters are removed from the getRequestURL(), which is NOT URL-Decoded. Because one is "/some directory" and the other is "/some%20directory" the removal of the late part is 2 characters fewer (1 space vs 3 characters in %20), and leaves two more characters: the extra "/s" is actually the two front characters of the "/some%20directory".
It's pretty awkward. I do not feel comfortable assuming any fix here.

I'm in the process of preparing a Pull-Request. I'm going to try and prepare two request with the two different approaches, since they're mutually exclusive.

**Comment by l-dobrev** [comment]
Created a new pull request #73 with a new attempt to solve the issue.
Removed handling of redirects, except for 304 which needs special handling.
Rewriting Location header even if not 304. As a nice side-effect 401 with Location header for authentication with REST services works.

**Comment by l-dobrev** [comment]
Thank you for helping and accepting the solution to the redirect-with-body problem.

I am working on proposing a change for the redirect Location with %-encoded characters in the URL (request or response). Feel free to close this issue and open/request a different issue for the URL handling.

**Comment by dsmiley** [comment]
I'd prefer that you create the issue about URL encoding fixes; please copy some of your text here so we don't need to refer back.  #34 has some related discussion.  Perhaps it's time to switch to getRequestURI instead of getPathInfo.

**Comment by dsmiley** [comment]
Nevermind; I see your pull request (no need for parallel issue).

**Comment by geezer78** [comment]
hi there,

i seem to have similar issues, but we're years later..
im trying to use an OAuth flow but it does not work and errors out on the step where i get an **302** with the redirect location in the header.

NullPointerException@166 "java.lang.NullPointerException: Cannot invoke "org.apache.http.Header.getValue()" because the return value of "org.apache.http.HttpEntity.getContentType()" is null"

when i change the code:

`if (statusCode == HttpServletResponse.SC_NOT_MODIFIED) {
                    // 304 needs special handling. See:
                    // http://www.ics.uci.edu/pub/ietf/http/rfc1945.html#Code304
                    // Don't send body entity/content!
                    servletResponse.setIntHeader(HttpHeaders.CONTENT_LENGTH, 0);
                } else {
                    // Send the content to the client
                    copyResponseEntity(proxyResponse, servletResponse, proxyRequest, servletRequest);
                }
`
                
                
to handle 302 the same way as 304 it works as expected.
