### ISSUE TITLE
Request Accessibility in copyResponseEntity()

### ISSUE THREAD

**Issue by BenjaminKlatt** [mitre/HTTP-Proxy-Servlet#76]
Hi, 

for improving the extensibility of the ProxyServlet in terms of response processing, please grant access to the request objects in the copyResponseEntity() method.

Required changes would be adding two additional parameters to the method body:
```java
protected void copyResponseEntity(HttpResponse proxyResponse, HttpServletResponse servletResponse, HttpRequest proxyRequest, HttpServletRequest servletRequest) throws IOException {
...
}
```

and adding the parameters to the according method invocation in the service() method:
```java
// Send the content to the client
copyResponseEntity(proxyResponse, servletResponse, proxyRequest, servletRequest);
```

Thanks
Benjamin

**Comment by kito99** [comment]
Cool. Any idea when this will be released?

**Comment by dsmiley** [comment]
Ah; not sure.  The last release was 6 months ago... so I think by the end of the month would be a good idea.  Feel free to prod me if I don't take action.
