### ISSUE TITLE
Add remark in readme about Spring Boot java configuration info

### ISSUE THREAD

**Issue by aldas** [mitre/HTTP-Proxy-Servlet#77]
Currently readme has examples only with xml configuration. Spring has moved to java configuration. Maybe it would be helpful to add block for Spring developer with example how to configure proxy in java. 

For example for Spring Boot application registering proxy servlet would be:

```java
@Configuration
public class SolrProxyServletConfiguration implements EnvironmentAware {

  private static final String ENV_PROXY_SOLR = "proxy.solr.";

  @Bean
  public ServletRegistrationBean servletRegistrationBean(){
    ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(new ProxyServlet(), propertyResolver.getProperty("servlet_url"));
    servletRegistrationBean.addInitParameter("targetUri", propertyResolver.getProperty("target_url"));
    servletRegistrationBean.addInitParameter(ProxyServlet.P_LOG, propertyResolver.getProperty("logging_enabled", "false"));
    return servletRegistrationBean;
  }

  private RelaxedPropertyResolver propertyResolver;

  @Override
  public void setEnvironment(Environment environment) {
    this.propertyResolver = new RelaxedPropertyResolver(environment, ENV_PROXY_SOLR);
  }
}
```

and properties in `application.yml`
```
proxy:
    solr:
        servlet_url: /solr/*
        target_url: http://solrserver:8983/solr
```

**Comment by dsmiley** [comment]
Ok; cool.  I haven't used Spring in a while.  Can you please provide me with a very simple means to run this so I can verify it works?  e.g. provide a pull request when a maven exec:run config that I ultimately never actually merge.... or perhaps you have another suggestion like emailing me a small zip  with some means to execute.  I could also simply just point to this issue from the README.md and not modify the readme.

**Comment by aldas** [comment]
I made little example Spring Boot project <https://github.com/aldas/mitre-proxy-servlet-spring-boot-example>

**Comment by dsmiley** [comment]
Neat.  Thanks for the example.  You should see it on the README.md now.
