### ISSUE TITLE
Make getTargetHost(HttpServletRequest) protected

### ISSUE THREAD

**Issue by irobertson** [mitre/HTTP-Proxy-Servlet#82]
I'm looking to write a reverse proxy which can proxy to more than one target host. This looks like ProxyServlet could be relatively easily extended to do this, if only getTargetHost(request) was protected like getTargetUri is.

If this seems a reasonable thing to do, I'm happy to submit a pull request, though that might be overkill for changing a single "private" to "protected" :).

If it helps, our use case is as follows. We have a number of services exposing various endpoints, and are in the process of moving some endpoints from one service to others. To avoid clients having to keep updating where they call, we need a reverse proxy that can decide where to proxy the request to based on its pathinfo, along with information it gets from each of the backing services at startup (each service has an endpoint listing all of its endpoints). From what I can tell, it would be sufficient to override getTargetUri and getTargetHost, but only the former is protected.

**Comment by dsmiley** [comment]
No prob; done.
