### ISSUE TITLE
Response from back server

### ISSUE THREAD

**Issue by prilia** [mitre/HTTP-Proxy-Servlet#87]
Hi,
Is it possible to get the response http from back server ?
Tnx !

**Comment by dsmiley** [comment]
Hi, ... I don't understand.  The response from the original server is sent through the server to the client; that's what a proxy does.  Maybe it's not doing this for you for some reason?

**Comment by prilia** [comment]
ok, understand ! Thank you !!!

**Comment by prilia** [comment]
Hello David,
Sorry for my miss understanding, but I want to ask one time the question.
So, first step - http request came from user to front server the data goes through the front server via proxy servlet to the back server. 
second step - back server gets the http request, does http response, that sends to front server and after it the front server sends it to the user.
Am I right ?
If so, is it possible to catch in front server response from back server before its sends to the client ?
Thank you !

**Comment by dsmiley** [comment]
Your description is right.
There is the copyResponseHeaders and copyResponseEntity methods you could override to customize/modify how the response is sent back.  It appears you can't change the status code if you want to though; that would require changes to the proxy.
