### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by LorandLorincz** [mitre/HTTP-Proxy-Servlet#95]
Hi, 
I just wanted to ask you if you have a roadmap regarding this Project. I would like to know when the next version will be release as I would like to use some features that are not yet available in 1.7.

Thanks.

**Comment by dsmiley** [comment]
Thanks for opening this issue.  I had planned to do a release a couple months ago but got sidetracked.  There is no official roadmap -- it's driven be people like you asking for a release and others submitting pull requests.  I'll shoot for doing a release by end of month.

**Comment by LorandLorincz** [comment]
Thanks for your response. It sure would help us a lot.
Keep up the good work, and I hope I will be able to contribute to this project in the future.

**Comment by dsmiley** [comment]
v1.8 is posted to Maven Central.
