### ISSUE TITLE
Hook to handle certain Response Codes(401)

### ISSUE THREAD

**Issue by LorandLorincz** [mitre/HTTP-Proxy-Servlet#98]
Hi,

We are using HTTP-Proxy-Servlet to integrate a 3rd Party App in our own app.
I would like to be able to handle 401 internally, without sending it to the client and convert our applications auth token and send it to the 3rd Party app.

Any advice?

**Comment by dsmiley** [comment]
Eh... none really.  I expect you can subclass the servlet to intercept 401 and do what you want.  If you can't I figure you'll find out real fast and then maybe we can consider ways to make the servlet more extensible if that happens.

**Comment by LorandLorincz** [comment]
Well I managed to implement the automatic authorization by subclassing the Servlet.
We still have one problem that will probably need a postExecute hook in the Servlet.

Basically this is what I'm doing. I'm checking if the request has the auth header.If not I add it and redo the request. If the Request has an auth header but the response is a 401(expired token) the I authorize the request and redo it.
`    protected void service(HttpServletRequest servletRequest, HttpServletResponse servletResponse) throws
        ServletException, IOException {
        if (proxyAuthProvider.hasAuthorizationHeader(servletRequest)) {
            super.service(servletRequest, servletResponse);
            if (proxyAuthProvider.notAuthorizedResponse(servletRequest, servletResponse)) {
                LOG.debug("Not Authorized Call. Trying to authenticate with proxied system.");
                authorizeAndService(servletRequest, servletResponse);
            }
        } else {
            authorizeAndService(servletRequest, servletResponse);
        }
    }

    private void authorizeAndService(HttpServletRequest servletRequest, HttpServletResponse servletResponse) throws
        IOException, ServletException {
        try {
            String changedAuthToken = proxyAuthProvider.doAuthorize(servletRequest, getProxyClient());

            HttpServletRequest authenticatedRequest =
                proxyAuthProvider.authorizeRequest(servletRequest, changedAuthToken);
            if (changedAuthToken != null) {
                authenticatedRequest.setAttribute(UMSYSTEM_AUTH_TOKEN, changedAuthToken);
            }
            super.service(authenticatedRequest, servletResponse);
        } catch (AuthenticationException e) {
            LOG.debug("Authorization failed.");
            LOG.debug("Request:" + servletRequest.getRequestURI());
            LOG.debug("Cookies:" + servletRequest.getCookies());
            servletResponse.setStatus(401);
        }
    }`

The first case works like a charm(pre authorize). The second case, when the token is expired still has some problems. That is because the first call to super.service consumen the entity and the response is directly sent to the client. 

This is why I need a postExecute hook, where I can handle the 401 before the entity is consumed.

Does it make sense, should I implement it and make a PR?

**Comment by dsmiley** [comment]
Hi. Perhaps you could achieve your aims by implementing a delegating or subclassed HttpClient overriding execute?  I'm not sure exactly what you're use case needs.  I do understand that ProxyServlet.service() is going to consume the request and send the response, but I'm unsure what could be done to help your use-case.

**Comment by LorandLorincz** [comment]
Well I ended up extracting the execute part of the service to a protected method so override it and implement the pre authentication and expired authentication case. It works well. Should I try and make a PR?

**Comment by dsmiley** [comment]
If it's just invoking the execute method on httpClient, then that sounds like a good thing to refactor out to a protected method that is over-rideable.  Yes, submit a PR please.

**Comment by LorandLorincz** [comment]
Pull request create #108
