### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by justin-r-oliver** [mitre/HTTP-Proxy-Servlet#99]
Hi,

Is there a way to increase the timeout on proxied requests?

Thanks

**Comment by dsmiley** [comment]
I would certainly expect so -- the Apache HttpClient/HttpComponents library is what this proxy uses, and that thing is quite flexible.  Look there for that option and you can customize it.

**Comment by justin-r-oliver** [comment]
Hi David,

Thanks for your reply. I decided to change by the default socket timeout by overriding the createHttpClient() method:

`    @Override
    protected HttpClient createHttpClient(HttpParams ignored) {

        RequestConfig defaultRequestConfig = RequestConfig.custom()
                .setSocketTimeout(Integer.getInteger(getConfigParam("httpClient.socketTimeout"), 60000))
                .build();

        CloseableHttpClient httpclient = HttpClients.custom()
                .setDefaultRequestConfig(defaultRequestConfig)
                .build();

        return httpclient;
    }
`

Cheers
